### PR TITLE
Fenixed

### PR DESCRIPTION
**Pull request by QuixoticFP**

### CODE REVIEW

**Comment by Dyneteve** [comment]
@QuixoticFP Yes fenix-ify it more

**Comment by Hlcpereira** [comment]
Wtf???

**Comment by andersonmendess** [comment]
😂

**Comment by shreejoy** [comment]
Excuse me WTF ???

**Comment by markakash** [comment]
Well, that was a very helpful pull request 😂

**Comment by ghost** [comment]
Lol 😂

**Comment by Akianonymus** [comment]
i love this guy 😍

**Comment by SwapnilSoni1999** [comment]
XD

**Comment by Rasenkai** [comment]
is this guy for real ?

**Comment by absarrahman** [comment]
Thugness overloaded

**Comment by Blacksuan19** [comment]
What in the fuck did you bring upon this cursed land

**Comment by Haseo97** [comment]
Lmao

**Review by Akianonymus — CHANGES_REQUESTED** [review]
The headers of the makefiles should be fenixfied too

Thx

**Comment by Yasir-siddiqui** [comment]
Thanks for fenix-ify :)

**Comment by yash-garg** [comment]
God won't forgive you for this !

**Comment by Yasir-siddiqui** [comment]
Lmao

**Review by Dyneteve — CHANGES_REQUESTED** [review]
Change license to fenix

**Review by Dyneteve — CHANGES_REQUESTED** [review]
Change license to fenix

**Comment by joeyhuab** [comment]
Jesus Christ.

**Comment by Dyneteve** [comment]
@Stallix yeah

**Comment by Jashkirat** [comment]
This guy for real. 😂😂 Sir you forgot to fenixfy the fenix_oneplus_3

**Comment by Dil3mm4** [comment]
A lot of zueira for Henrique with all this notifs.

**Comment by ronellsalunke** [comment]
Ah shit here we go again

**Comment by Abhinavgupta371** [comment]
Wow sar u so peru please teach us we all nubs

**Comment by Dyneteve** [comment]
@Abhinavgupta371 20$ per guide how to fenix

**Comment by Subinsmani** [comment]
Wow cooool... Fenix is everywhere... 🤣

**Comment by anayw2001** [comment]
wau sir dev so pru
ETA wen

**Comment by calvinadrien** [comment]
sirrr wen tissot build sirrrrr

**Comment by x-Pepsy** [comment]
DIO MAIALE! A new superhero is born: Kangerman

**Comment by beingmishra** [comment]
Comments are more interesting than commit lmao :stuck_out_tongue_closed_eyes:

**Comment by Abhinavgupta371** [comment]
@Dyneteve bruh 69$ we nub he will have to work on us wee fucking nubsss

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by beingmishra** [comment]
@Abhinavgupta371 yeah we know u noob ... Tell new shit....  Kbye

**Comment by johnlaff** [comment]
LOOOL, Not every hero uses a cape rofl

**Comment by johnlaff** [comment]
LOOL, Not every hero uses a cape

**Comment by jhenrique09** [comment]
Stop with these bullshits, thanks

**Comment by Blacksuan19** [comment]
Oof

**Comment by Abhinavgupta371** [comment]
@beingmishra moi gawd ;__;

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Abhinavgupta371** [comment]
@jhenrique09 as u say !

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
